name: Zip and Send .bru Files to Slack

on:
  push:
    branches:
      - main

jobs:
  zip-and-send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Zip .bru files
      run: |
        mkdir -p bru_files
        find . -name "*.bru" -exec cp {} bru_files/ \;
        zip -r bru_files.zip bru_files

    - name: Send to Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl -F file=@bru_files.zip -F "initial_comment=Here are the latest .bru files from the merged PR." -F channels=#your-channel-name -H "Authorization: Bearer $SLACK_WEBHOOK_URL" https://slack.com/api/files.upload
